plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - breaking: true
          release: major
        - type: build # Changes that affect the build system or external dependencies
          release: patch
        - type: chore # Other changes that don't modify src or test files
          release: false
        - type: ci # Changes to our CI configuration files and scripts
          release: false
        - type: docs # Documentation only changes
          release: patch
        - type: feat # A new feature
          release: minor
        - type: fix # A bug fix
          release: patch
        - type: perf # A code change that improves performance
          release: patch
        - type: refactor # A code change that neither fixes a bug nor adds a feature
          release: false
        - type: revert # Reverts a previous commit
          release: patch
        - type: style # Changes that do not affect the meaning of the code
          # (white-space, formatting, missing semi-colons, etc)
          release: false
        - type: test # Adding missing tests or correcting existing tests
          release: false
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
#  - - "@semantic-release/exec"
#    - prepareCmd:
#      - "sed -i \"s/^version: .*/version: ${nextRelease.version}/g\" pubspec.yaml"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - pubspec.yaml
#      message: |-
#        chore(release): ${nextRelease.version} [skip ci]
#        ${nextRelease.notes}
branches:
  - name: "develop"
debug: false
